feat: [DOCS-152] added submit button handler
seamlesspay/web-sdk-examples pull request #1
Opened 2024-05-21 14:33 UTC by ikalinichenko

2024-05-21 14:57 UTC, wyattisimo requested changes

2024-05-21 14:57 UTC, wyattisimo commented on hosted-fields/index.js
> +    hostedFields.addSubmitHandler(submitHandler, paymentData);
@ikalinichenko It's unlikely that this `paymentData` would be available upon initialization because it's usually populated by the end-user. We need to facilitate this inside the submit handler.

2024-05-21 15:53 UTC, ikalinichenko commented on hosted-fields/index.js
> +    hostedFields.addSubmitHandler(submitHandler, paymentData);
@wyattisimo, should it be like this?

```javascript
function hostedFieldsDidCreate(error, hostedFieldsInstance) {
  hostedFields.addSubmitHandler(submitHandler);
  hostedFields.setPaymentData(paymentData);
}

function submitHandler(error, payload) {
 const token = payload.token;
}
```

2024-05-22 14:21 UTC, wyattisimo approved these changes

2024-05-22 14:50 UTC, merged